- hosts: buildah
  become: yes

  tasks:
  - name: BUILDAH | Test output of "buildah images <image_name>" command
    buildah_images:
      name: docker.io/library/fedora
      truncate: yes
    register: result

  - debug: var=result.stdout_lines

  - name: BUILDAH | Test JSON output of "buildah images --json <image_name>" command
    buildah_images:
      name: docker.io/library/fedora
      json: yes
    register: result

  - debug: var=result.stdout_lines

  - name: BUILDAH | Test output of "buildah images --no-trunc <image_name>" command
    buildah_images:
      name: docker.io/library/fedora
      truncate: no
    register: result

  - debug: var=result.stdout_lines

# #######################  DOES NOT WORK YET ###################################
#   - name: BUILDAH | Test output of "buildah images <FORMAT> <image_name>" command
#     buildah_images:
#       name: docker.io/library/fedora
#       format: 'ID: {{.ID}} Name: {{.Name}} Digest: {{.Digest}} Created: {{.CreatedAt}} Size: {{.Size}}'
#     register: result
#     tags:
#       - go

#   - debug: var=result.stdout_lines
#     tags:
#       - go
# #######################  DOES NOT WORK YET ###################################

  - name: BUILDAH | Test output of "buildah images --noheading <image_name>" command
    buildah_images:
      name: docker.io/library/fedora
      heading: no
    register: result

  - debug: var=result.stdout_lines

  - name: BUILDAH | Test output of ALL "buildah images" command
    buildah_images:
      name:    # Empty name: results in ALL images - REVISIT
    register: result

  - debug: var=result.stdout_lines
