- hosts: buildah
  become: yes

  tasks:
  - name: BUILDAH | Test output of "buildah add " command
    buildah_add:
      name: 32282b25dcb9
      src: HelloWorld.txt
      dest: /tmp/HelloWorld.txt
    register: result

  - debug: var=result.stdout_lines

