- hosts: buildah
  become: yes

  tasks:
  - name: BUILDAH | Test "buildah rename <container_name/ID> <new_container_name>" command
    buildah_rename:
      container_name: 8c85c9fab053
      new_container_name: fedora-working-container-renamed
    register: result

  - debug: var=result.stdout_lines
