- hosts: buildah
  become: yes

  tasks:
  - name: BUILDAH | Test output of "buildah mount using container_name" command
    buildah_mount:
      name: working-container
      truncate: yes
    register: result

  - debug: var=result

  - name: BUILDAH | Test output of "buildah mount using container ID" command
    buildah_mount:
      name: 79f3b6b5804f
    register: result

  - debug: var=result
